# Generated by Django 5.2.17 on 2026-09-25 02:41

import core_api.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_mcp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=64, unique=True)),
                ('client_secret_hash', models.CharField(blank=True, max_length=64)),
                ('token_endpoint_auth_method', models.CharField(default='none', max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('redirect_uris', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthAuthorizationCode',
            fields=[
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('user_id', models.CharField(max_length=64)),
                ('redirect_uri', models.TextField()),
                ('code_challenge', models.CharField(max_length=128)),
                ('scope', models.CharField(blank=True, max_length=200)),
                ('resource', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platform_mcp.oauthclient')),
            ],
        ),
        migrations.CreateModel(
            name='OAuthGrant',
            fields=[
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('scope', models.CharField(blank=True, max_length=200)),
                ('resource', models.TextField(blank=True)),
                ('refresh_token_hash', models.CharField(max_length=64, unique=True)),
                ('refresh_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='platform_mcp.oauthclient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuthAccessToken',
            fields=[
                ('id', models.UUIDField(default=core_api.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='platform_mcp.oauthgrant')),
            ],
        ),
    ]
